name: "klimowska-a"

services:
  server:
    command: ["python3", "-m", "http.server", "8000"]
    image: "python:3.13-slim"
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ../a
        target: /app/a
      - type: bind
        source: ./
        target: /app/a-src
    working_dir: "/app"
